# Generated by Django 4.2.7 on 2023-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_remove_question_expectation_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Tags',
            field=models.CharField(max_length=100),
        ),
    ]
