# Generated by Django 4.2.7 on 2023-12-01 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
