# Generated by Django 4.2.7 on 2023-12-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_question_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='posted_at',
        ),
    ]
