# Generated by Django 4.2.7 on 2023-12-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_questionvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionvote',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], default='up', max_length=4),
            preserve_default=False,
        ),
    ]
