# Generated by Django 4.2.7 on 2023-12-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0017_delete_userinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookMarked',
        ),
    ]
