# Generated by Django 4.2.7 on 2023-12-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0020_userinformation_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarked',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.answer'),
        ),
        migrations.AlterField(
            model_name='bookmarked',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.question'),
        ),
    ]
