# Generated by Django 4.2.7 on 2023-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0021_alter_bookmarked_answer_alter_bookmarked_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarked',
            name='isBookMarked',
            field=models.BooleanField(default=False),
        ),
    ]
