# Generated by Django 4.2.7 on 2023-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_bookmarked_isbookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='Profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
